```{r}
library(corrplot)
library(tidyr)
```

```{r}
data = read.csv("cumulative.csv")
```

```{r}
keep_vars <- c(
  "koi_disposition",
  "koi_period", "koi_impact", "koi_duration", "koi_depth",
  "koi_prad", "koi_teq", "koi_insol",
  "koi_model_snr",
  "koi_steff", "koi_slogg", "koi_srad",
  "koi_kepmag",
  "koi_score"
)

kepler_clean <- data[, keep_vars]; kepler_clean

# optional to remove non-dispositioned
kepler_clean <- kepler_clean[
    kepler_clean$koi_disposition == "CONFIRMED" |
    kepler_clean$koi_disposition == "FALSE POSITIVE",
]

kepler_clean$koi_disposition <- factor(kepler_clean$koi_disposition)

summary(kepler_clean)

```

```{r}
colSums(is.na(kepler_clean))

# omit all NA values in the cleaned dataset
kepler_clean <- kepler_clean %>% drop_na()

colSums(is.na(kepler_clean)) 
```

```{r}
trim_limits <- function(x) {
    q_low  <- quantile(x, 0.01, na.rm = TRUE)
    
    
    
    
        q_high <- quantile(x, 0.99, na.rm = TRUE)
    return(c(q_low, q_high))
}
```

```{r}
lims <- quantile(kepler_clean$koi_prad, c(0.01, 0.95), na.rm = TRUE)

x <- kepler_clean$koi_prad
x_trimmed <- x[ x >= lims[1] & x <= lims[2] ]

# 1 = the radius of Earth.
hist(x_trimmed,
     main = "Planet Radius (trimmed to 1%-95%)",
     xlab = "Planet Radius (Earth radii)",
     col = "lightblue",
     breaks = 30)


lims <- quantile(kepler_clean$koi_period, c(0.01, 0.95), na.rm = TRUE)

x <- kepler_clean$koi_period
x_trimmed <- x[ x >= lims[1] & x <= lims[2] ]

hist(x_trimmed,
     main = "Orbital Period (trimmed to 1%-95%)",
     xlab = "Orbital Period (days)",
     col = "lightblue",
     breaks = 30)


lims <- quantile(kepler_clean$koi_depth, c(0.01, 0.9), na.rm = TRUE)

x <- kepler_clean$koi_depth
x_trimmed <- x[ x >= lims[1] & x <= lims[2] ]

hist(x_trimmed,
     main = "Transit Depth (trimmed to 1%-95%)",
     xlab = "Transit Depth (ppm)",
     col = "lightblue",
     breaks = 30)

lims <- quantile(kepler_clean$koi_teq, c(0.01, 0.99), na.rm = TRUE)

x <- kepler_clean$koi_teq
x_trimmed <- x[ x >= lims[1] & x <= lims[2] ]

hist(x_trimmed,
     main = "Equilibrium Temperature (trimmed to 1%-95%)",
     xlab = "Equilibrium Temperature (K)",
     col = "lightblue",
     breaks = 30)


x <- kepler_clean$koi_prad
lims <- quantile(x, c(0.01, 0.95), na.rm = TRUE)

boxplot(koi_prad ~ koi_disposition,
        data = kepler_clean,
        main = "Planet Radius by Disposition (1%-95% y-trim)",
        xlab = "Disposition",
        ylab = "Planet Radius (Earth radii)",
        ylim = lims)

x <- kepler_clean$koi_depth
lims <- quantile(x, c(0.01, 0.90), na.rm = TRUE)

boxplot(koi_depth ~ koi_disposition,
        data = kepler_clean,
        main = "Transit Depth by Disposition (1%-90% y-trim)",
        xlab = "Disposition",
        ylab = "Transit Depth (ppm)",
        ylim = lims)


x <- kepler_clean$koi_model_snr
lims <- quantile(x, c(0.01, 0.95), na.rm = TRUE)

boxplot(koi_model_snr ~ koi_disposition,
        data = kepler_clean,
        main = "Transit SNR by Disposition (1%-95% y-trim)",
        xlab = "Disposition",
        ylab = "Model SNR",
        ylim = lims)


x <- kepler_clean$koi_prad
y <- kepler_clean$koi_depth

xlims <- quantile(x, c(0.01, 0.95), na.rm = TRUE)
ylims <- quantile(y, c(0.01, 0.95), na.rm = TRUE)

plot(x, y,
     main = "Transit Depth vs Planet Radius (1%-95% trimmed)",
     xlab = "Planet Radius (Earth radii)",
     ylab = "Transit Depth (ppm)",
     col  = "darkgray",
     xlim = xlims,
     ylim = ylims)


x <- kepler_clean$koi_steff
y <- kepler_clean$koi_srad

xlims <- quantile(x, c(0.01, 0.95), na.rm = TRUE)
ylims <- quantile(y, c(0.01, 0.95), na.rm = TRUE)

plot(x, y,
     main = "Stellar Radius vs Effective Temperature (1%-95% trimmed)",
     xlab = "Stellar Effective Temperature (K)",
     ylab = "Stellar Radius (solar radii)",
     col  = "darkgray",
     xlim = xlims,
     ylim = ylims)

disp_table <- table(kepler_clean$koi_disposition)

barplot(disp_table,
        main = "Counts by Disposition",
        xlab = "Disposition",
        ylab = "Count",
        col  = c("lightgreen", "salmon"))

```

```{r}
x <- kepler_clean$koi_score
lims <- quantile(x, c(0.01, 0.99), na.rm = TRUE)
x_trimmed <- x[x >= lims[1] & x <= lims[2]]

hist(x_trimmed,
     main = "KOI Disposition Score (1%-99% trimmed)",
     xlab = "koi_score",
     col = "lightblue",
     breaks = 30)


x <- kepler_clean$koi_score
lims <- quantile(x, c(0.01, 0.99), na.rm = TRUE)

boxplot(koi_score ~ koi_disposition,
        data = kepler_clean,
        main = "KOI Score by Disposition",
        xlab = "Disposition",
        ylab = "KOI Score",
        ylim = lims)

confirmed_rows <- kepler_clean$koi_disposition == "CONFIRMED"
false_rows     <- kepler_clean$koi_disposition == "FALSE POSITIVE"

x <- kepler_clean$koi_depth
y <- kepler_clean$koi_score

xlims <- quantile(x, c(0.01, 0.95), na.rm = TRUE)
ylims <- quantile(y, c(0.01, 0.99), na.rm = TRUE)

plot(x[confirmed_rows], y[confirmed_rows],
     col = "blue", pch = 16,
     main = "KOI Score vs Transit Depth",
     xlab = "Transit Depth (ppm)",
     ylab = "KOI Score",
     xlim = xlims,
     ylim = ylims)

points(x[false_rows], y[false_rows],
       col = "red", pch = 16)

legend("topright", legend = c("Confirmed", "False Positive"),
       col = c("blue", "red"), pch = 16)


confirmed_rows <- kepler_clean$koi_disposition == "CONFIRMED"
false_rows     <- kepler_clean$koi_disposition == "FALSE POSITIVE"

x <- kepler_clean$koi_model_snr
y <- kepler_clean$koi_score

xlims <- quantile(x, c(0.01, 0.95), na.rm = TRUE)
ylims <- quantile(y, c(0.01, 0.99), na.rm = TRUE)

plot(x[confirmed_rows], y[confirmed_rows],
     col = "blue", pch = 16,
     main = "KOI Score vs Transit SNR",
     xlab = "Transit SNR",
     ylab = "KOI Score",
     xlim = xlims,
     ylim = ylims)

points(x[false_rows], y[false_rows],
       col = "red", pch = 16)

legend("topright", legend = c("Confirmed", "False Positive"),
       col = c("blue", "red"), pch = 16)

x <- kepler_clean$koi_prad
y <- kepler_clean$koi_score

xlims <- quantile(x, c(0.01, 0.95), na.rm = TRUE)
ylims <- quantile(y, c(0.01, 0.99), na.rm = TRUE)

plot(x[confirmed_rows], y[confirmed_rows],
     col = "blue", pch = 16,
     main = "KOI Score vs Planet Radius",
     xlab = "Planet Radius (Earth radii)",
     ylab = "KOI Score",
     xlim = xlims,
     ylim = ylims)

points(x[false_rows], y[false_rows],
       col = "red", pch = 16)

legend("topright", legend = c("Confirmed", "False Positive"),
       col = c("blue", "red"), pch = 16)


x <- kepler_clean$koi_duration
y <- kepler_clean$koi_score

xlims <- quantile(x, c(0.01, 0.95), na.rm = TRUE)
ylims <- quantile(y, c(0.01, 0.99), na.rm = TRUE)

plot(x[confirmed_rows], y[confirmed_rows],
     col = "blue", pch = 16,
     main = "KOI Score vs Transit Duration",
     xlab = "Transit Duration (hours)",
     ylab = "KOI Score",
     xlim = xlims,
     ylim = ylims)

points(x[false_rows], y[false_rows],
       col = "red", pch = 16)

legend("topright", legend = c("Confirmed", "False Positive"),
       col = c("blue", "red"), pch = 16)

x <- kepler_clean$koi_steff
y <- kepler_clean$koi_score

xlims <- quantile(x, c(0.01, 0.95), na.rm = TRUE)
ylims <- quantile(y, c(0.01, 0.99), na.rm = TRUE)

plot(x[confirmed_rows], y[confirmed_rows],
     col = "blue", pch = 16,
     main = "KOI Score vs Stellar Effective Temperature",
     xlab = "Stellar Temperature (K)",
     ylab = "KOI Score",
     xlim = xlims,
     ylim = ylims)

points(x[false_rows], y[false_rows],
       col = "red", pch = 16)

legend("topright", legend = c("Confirmed", "False Positive"),
       col = c("blue", "red"), pch = 16)

x <- kepler_clean$koi_srad
y <- kepler_clean$koi_score

xlims <- quantile(x, c(0.01, 0.95), na.rm = TRUE)
ylims <- quantile(y, c(0.01, 0.99), na.rm = TRUE)

plot(x[confirmed_rows], y[confirmed_rows],
     col = "blue", pch = 16,
     main = "KOI Score vs Stellar Radius",
     xlab = "Stellar Radius (solar radii)",
     ylab = "KOI Score",
     xlim = xlims,
     ylim = ylims)

points(x[false_rows], y[false_rows],
       col = "red", pch = 16)

legend("topright", legend = c("Confirmed", "False Positive"),
       col = c("blue", "red"), pch = 16)

x <- kepler_clean$koi_prad
y <- kepler_clean$koi_srad

xlims <- quantile(x, c(0.01, 0.95), na.rm = TRUE)
ylims <- quantile(y, c(0.01, 0.95), na.rm = TRUE)

plot(x[confirmed_rows], y[confirmed_rows],
     col = "blue", pch = 16,
     main = "Planet Radius vs Stellar Radius (colored by disposition)",
     xlab = "Planet Radius (Earth radii)",
     ylab = "Stellar Radius (solar radii)",
     xlim = xlims,
     ylim = ylims)

points(x[false_rows], y[false_rows],
       col = "red", pch = 16)

legend("topright", legend = c("Confirmed", "False Positive"),
       col = c("blue", "red"), pch = 16)

```

```{r}
# One-way ANOVA tests with categorical variable disposition

# transit depth vs disposition
c("Transit Depth vs Disposition")
transit <- aov(koi_depth ~ koi_disposition, data = kepler_clean)
summary(transit)
plot(TukeyHSD(transit))


# signal-to-noise vs disposition
c("Signal-to-Noise vs Disposition")
snr <- aov(koi_model_snr ~ koi_disposition, data = kepler_clean)
summary(snr)
plot(TukeyHSD(snr))


# planet radius vs disposition
c("Planet Radius vs Disposition")
prad <- aov(koi_prad ~ koi_disposition, data = kepler_clean)
summary(prad)
plot(TukeyHSD(prad))


# orbital period vs disposition
c("Orbital Period vs Disposition")
orbital_period <- aov(koi_period ~ koi_disposition, data = kepler_clean)
summary(orbital_period)
plot(TukeyHSD(orbital_period))


# stellar temperature vs disposition
c("Stellar Temperature vs Disposition")
stellar_temp <- aov(koi_steff ~ koi_disposition, data = kepler_clean)
summary(stellar_temp)
plot(TukeyHSD(orbital_period))


# transit duration vs disposition
c("Transit Duration vs Disposition")
transit_duration <- aov(koi_duration ~ koi_disposition, data = kepler_clean)
summary(transit_duration)
plot(TukeyHSD(transit_duration))


# impact parameter vs disposition
c("Impact Parameter vs Disposition")
impact_param <- aov(koi_impact ~ koi_disposition, data = kepler_clean)
summary(impact_param)
plot(TukeyHSD(impact_param))


# insolation flux vs disposition
c("Insolation Flux vs Disposition")
insol_flux <- aov(koi_insol ~ koi_disposition, data = kepler_clean)
summary(insol_flux)
plot(TukeyHSD(insol_flux))
```


```{r}
# Two-way ANOVA tests 

# transit depth affected by disposition and star temperature
kepler_clean$teff_bin <- cut(kepler_clean$koi_steff, 
                             breaks = c(-Inf, 4500, 5500, 6500, Inf),
                             labels = c("Cool", "Sunlike", "Warm", "Hot"))
star_temp <- aov(koi_depth ~ koi_disposition * teff_bin, data = kepler_clean)
summary(star_temp)
plot(TukeyHSD(star_temp))


# transit duration affected by radius category and disposition
kepler_clean$radius_group <- cut(kepler_clean$koi_prad, 
                    breaks = c(-Inf, 1.25, 2, 4, Inf), 
                    labels = c("Earth", "SuperEarth", "SubNeptune",
                               "Neptune+"))
duration_diffs <- aov(koi_duration ~ radius_group * koi_disposition, data = kepler_clean)
summary(duration_diffs)
plot(TukeyHSD(duration_diffs))


# insolation flux affected by disposition and stellar radius bin
kepler_clean$rstar_bin <- cut(kepler_clean$koi_srad, breaks = 4)
irradiation_diffs <- aov(koi_insol ~ koi_disposition *rstar_bin, data = kepler_clean)
summary(irradiation_diffs)
plot(TukeyHSD(irradiation_diffs))
```
```{r}
# Other ANOVA tests

# control planet radius while testing affect of transit depth by disposition
aov(koi_depth ~ koi_disposition + koi_prad, data = kepler_clean)

# multivariable analysis
manova(cbind(koi_depth, koi_duration, koi_prad) ~ koi_disposition, data = kepler_clean)
```

### Testing to see if our data naturally fits into groups
### K-means (k=2)
```{r}
# Reset kepler_clean
keep_vars <- c(
  "koi_disposition",
  "koi_period", "koi_impact", "koi_duration", "koi_depth",
  "koi_prad", "koi_teq", "koi_insol",
  "koi_model_snr",
  "koi_steff", "koi_slogg", "koi_srad",
  "koi_kepmag",
  "koi_score"
)

kepler_clean <- data[, keep_vars]
kepler_clean <- kepler_clean %>% drop_na()

kmeans_data = subset(kepler_clean, select = -koi_disposition)


km.out = kmeans(kmeans_data, 2, nstart = 50)
cluster = factor(km.out$cluster)

kepler_with_clusters <- kepler_clean
kepler_with_clusters <- cbind(kepler_with_clusters, cluster)

cluster_counts <- table(
  disposition = kepler_with_clusters$koi_disposition,
  cluster     = kepler_with_clusters$cluster
)

print(cluster_counts)
# That's pretty one-sided...

```


```{r}
# What if we scale the data?
kmeans_data = scale(kmeans_data)

km.out = kmeans(kmeans_data, 2, nstart = 50)
cluster = factor(km.out$cluster)

kepler_with_clusters <- kepler_clean
kepler_with_clusters <- cbind(kepler_with_clusters, cluster)

cluster_counts <- table(
  disposition = kepler_with_clusters$koi_disposition,
  cluster     = kepler_with_clusters$cluster
)

print(cluster_counts)

library(ggplot2)

ggplot(as.data.frame(cluster_counts),
       aes(x = cluster, y = Freq, fill = disposition)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Confirmed vs False Positive Across K-means Clusters",
    x = "Cluster",
    y = "Count",
    fill = "Disposition"
  )

```
Around a third of false positives suddenly filled up the other cluster, with most of the confirmed points sticking to one cluster.

### Hierarchical clustering
```{r}
par(mfrow = c(1,3))
# should be scaled from the previous block
# kmeans_data = scale(kmeans_data)
hc.complete = hclust(dist(kmeans_data), method = "complete")
hc.average = hclust(dist(kmeans_data), method = "average")
hc.single = hclust(dist(kmeans_data), method = "single")
plot(hc.complete)
plot(hc.average)
plot(hc.single)

```
```{r}
# Cut the tree?
cluster = factor(cutree(hc.average, h = 20))

kepler_with_clusters <- kepler_clean
kepler_with_clusters <- cbind(kepler_with_clusters, cluster)

cluster_counts <- table(
  disposition = kepler_with_clusters$koi_disposition,
  cluster     = kepler_with_clusters$cluster
)

print(cluster_counts)

# It's pretty obvious that this won't work well.
# Overall it tells us that our data doesn't naturally fit into nice groups without labels. Supervised learning is the way to go!

```

###Trees

```{r}
library(tree)
library(randomForest)
library(ipred)
library(gbm)
set.seed(123)

# 70/30 split of data
n <- nrow(kepler_clean)
train_idx <- sample(seq_len(n), size = 0.7 * n)

train <- kepler_clean[train_idx, ]
test  <- kepler_clean[-train_idx, ]
```


# Simple classification tree using all predictors
```{r}
tree_fit <- tree(koi_disposition ~ ., data = train)

summary(tree_fit)
plot(tree_fit)
text(tree_fit, pretty = 0, cex = 0.7)
title("Classification Tree for KOI Disposition")

tree_pred <- predict(tree_fit, newdata = test, type = "class")
tree_acc  <- mean(tree_pred == test$koi_disposition)

tree_acc
```

#random forest
```{r}
rf_fit <- randomForest(koi_disposition ~ ., data = train, ntree = 300, importance = TRUE)
rf_fit

varImpPlot(rf_fit, main = "Random Forest Variable Importance")

rf_pred <- predict(rf_fit, newdata = test, type = "class")
rf_acc <- mean(rf_pred == test$koi_disposition)

rf_acc
```

#bagging
```{r}
bag_fit <- bagging(koi_disposition ~ ., data = train, nbagg = 200)
bag_fit

bag_pred <- predict(bag_fit, newdata = test, type = "class")
bag_acc <- mean(bag_pred == test$koi_disposition)

bag_acc
```

#boosting
```{r}
boost_train <- train
boost_test  <- test

boost_train$y <- ifelse(boost_train$koi_disposition == "CONFIRMED", 1, 0)
boost_test$y  <- ifelse(boost_test$koi_disposition == "CONFIRMED", 1, 0)

boost_fit <- gbm(y ~ . - koi_disposition, data = boost_train, distribution = "bernoulli", n.trees = 2000, interaction.depth = 3,
                 shrinkage = 0.01, n.minobsinnode = 10, cv.folds = 5, verbose = FALSE)

best_iter <- gbm.perf(boost_fit, method = "cv")
best_iter

plot(boost_fit, i = "koi_score", n.trees = best_iter,
main = "Boosting Partial Dependence: KOI Score")

boost_prob <- predict(boost_fit, newdata = boost_test, n.trees = best_iter, type = "response")

boost_pred <- ifelse(boost_prob > 0.5, "CONFIRMED", "FALSE POSITIVE")
boost_pred <- factor(boost_pred, levels = levels(test$koi_disposition))

boost_acc <- mean(boost_pred == test$koi_disposition)

boost_acc
```

#final comparison
```{r}
data.frame(
Model = c("Classification Tree", "Random Forest", "Bagging", "Boosting"),
Accuracy = c(tree_acc, rf_acc, bag_acc, boost_acc)
)

```
